### ISSUE TITLE
Single log per request

### ISSUE THREAD

**Issue by pylover** [elahe-dastan/urlShortener_KGS#2]

**Comment by 1995parham** [comment]
There is an excellent package for logging in Golang, and I think this would be useful for logging with multiple attributes. [logrus](https://pkg.go.dev/github.com/sirupsen/logrus?tab=doc)

**Comment by pylover** [comment]
Disagree, please print a single line for every request by yourself. A simple print statement shouldn't lead us to add another dependency.
