### ISSUE TITLE
Separate entry point for database initialization.

### ISSUE THREAD

**Issue by pylover** [elahe-dastan/urlShortener_KGS#3]

**Comment by 1995parham** [comment]
One way for separating the database initiation phase is providing a final binary with multiple commands like:

```sh
urlShortener server # this will run the server
urlShortener migrate # this will run the database initiation
```

for creating the above binary, one way is to use the [cobra](https://pkg.go.dev/github.com/spf13/cobra?tab=doc) package.

**Comment by pylover** [comment]
Like it. please use `setupdb` instead of `migraet`.
